# a workflow that sends a telegram message when a new release is published
name: Release Announcement
on:
  push:
    branches:
      - main

jobs:
  release-announcement:
    runs-on: ubuntu-latest
    steps:
      - name: get-package-version
        run: |
          echo "PACKAGE_VERSION=$(node -p "require('./package.json').version")" >> $GITHUB_ENV
      - name: get-changelog
        run: |
          echo "CHANGELOG=$(git log --pretty=format:'%s' --abbrev-commit --no-merges --reverse $(git describe --tags --abbrev=0)..HEAD)" >> $GITHUB_ENV
      - name: Release Announcement
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_TO }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          message: |
            🌩New types published🌩
            Version: ${{ env.PACKAGE_VERSION }}
            Changelog:
            ${{ env.CHANGELOG }}
