# a workflow that sends a telegram message when a new release is published
name: Release Announcement
on:
  push:
    branches:
      - main

jobs:
  get_package_version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: cat package.json | jq -r .version
        id: package_version
  release-announcement:
    runs-on: ubuntu-latest
    needs: get_package_version
    steps:
      - name: Release Announcement
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_TO }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          message: |
            🌩New types published🌩: ${{ steps.get_package_version.outputs.package_version }}
            ${{ github.event.release.html_url }}
